export const LOAD_DATA_COUNTRIES = "LOAD_DATA_COUNTRIES";
export const LOAD_DATA_COUNTRIES_SUCCESS = "LOAD_DATA_COUNTRIES_SUCCESS";
export const LOAD_DATA_COUNTRIES_FAILED = "LOAD_DATA_COUNTRIES_FAILED";
export const FILTER_DATA_COUNTRIES_SEARCH = "FILTER_DATA_COUNTRIES_SEARCH";
